const form = {
  secoes:[
 {
    "nome": "Dados gerais",
    "campos": [
      /*{"id": "1.1", "pergunta": "Unidade correicionada:.", "tipo": "text"},*/
      {"id": "3", "pergunta": "Órgão(s) jurisdicional(is) perante o(s) qual(is) atua.", "tipo": "textarea"},
     
      {"id": "1.3", "pergunta": "Membro Correicionado", "tipo": "textarea"},
      {"id": "1.4", "pergunta": "Designação", "tipo": "radio","opcoes":["Titular","Ampliado"]},
      /* {"id": "1", "pergunta": "Ato(s) normativo(s) que fixa(m) as atribuições do órgão correicionado (com indicação dos artigos).", "tipo": "textarea"}//,
     {"id": "2", "pergunta": "Descrição detalhada das atribuições.", "tipo": "textarea"}//,
      {"id": "4", "pergunta": "Municípios que compõem a área de atuação e população abrangida.", "tipo": "textarea"} ( solicitado remover)*/
      


    ]
  },
  {
    "nome": "Dados do membro",
    "campos": [
      {"id": "5", "pergunta": "Data em que assumiu o órgão correicionado.", "tipo": "date"},
      {"id": "6", "pergunta": "Reside na comarca de lotação?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "6.a", "pergunta": "Em caso negativo, informar o ato autorizativo.", "tipo": "textarea", dependeDe: { id: "6", valor: "Não" }},
      {"id": "7", "pergunta": "Com que regularidade comparece à Promotoria de Justiça?", "tipo": "textarea"},
      {"id": "8", "pergunta": "O(a) membro(a) tem autorização para a realização de trabalho remoto?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "8.b", "pergunta": "Em caso positivo, informar o período total autorizado para a realização do trabalho remoto;", "tipo": "date_ranger" , "inicioLabel": "INICIO", "fimLabel": "FIM"},//colocar dias da semana e periodo 
      {"id": "8.a", "pergunta": "Em caso positivo, especificar: o ato autorizativo correspondente; e os dias da semana em que o trabalho remoto é permitido, caso a autorização não contemple todos os dias úteis.", "tipo": "textarea", dependeDe: { id: "8", valor: "Sim" }},//colocar dias da semana e periodo 
       {"id": "9.d", "pergunta": "De que forma participa das audiências judiciais?", "tipo": "radio", "opcoes": ["Presencial", "Virtual","Ambas"]},
      
      {"id": "9", "pergunta": "Participa das audiências judiciais utilizando o computador da promotoria?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "9.a", "pergunta": "Em caso negativo, justificar, informando a hipótese legal prevista na regulamentação interna.", "tipo": "textarea", dependeDe: { id: "9", valor: "Não" }},
      {"id": "9.b", "pergunta": "Realiza audiências extrajudiciais de forma presencial?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "9.c", "pergunta": "Em caso negativo, justificar, informando a hipótese legal prevista na regulamentação interna.", "tipo": "textarea", dependeDe: { id: "9.b", valor: "Não" }},
      {"id": "10", "pergunta": "Nos últimos 12 meses, participou de curso(s) de aperfeiçoamento sobre autocomposição, atuação resolutiva ou temas afins a sua área de atuação?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "10.a", "pergunta": "Caso tenha participado de curso de aperfeiçoamento, informar os cursos e as datas de participação.","tipo": "textarea", dependeDe: { id: "10", valor: "Sim" }},
      {"id": "10.b", "pergunta": "Em caso positivo, realizou averbação dos cursos?","tipo": "radio", "opcoes": ["Sim", "Não"], dependeDe: { id: "10", valor: "Sim" }},
      {"id": "11", "pergunta": "Recebeu prêmio, homenagem, anotação ou elogio no prontuário em decorrência de sua atuação nos últimos 12 meses?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "11.a", "pergunta": "Especificar.", "tipo": "textarea", dependeDe: { id: "11", valor: "Sim" }},
      {"id": "12", "pergunta": "Exerce magistério (Resolução CNMP nº 73/2011)?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "12.a", "pergunta": "Exerce magistério?", "tipo": "radio", "opcoes": ["Virtual", "Presencial","Ao vivo/On-line"], dependeDe: { id: "12", valor: "Sim" }},
      {"id": "12.b", "pergunta": "No caso de exercer magistério, informar os horários em que ministra ou grava as aulas e a carga horária mensal dedicados ao ensino.", "tipo": "textarea", dependeDe: { id: "12", valor: "Sim" }},
      {"id": "13", "pergunta": "Exerce as atividades de mentoria/coaching não remunerada, ou similares e congêneres, destinadas à assessoria individual ou coletiva de pessoas, inclusive na preparação de candidatos a concursos públicos (Resolução CNMP nº 224/2021)?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "13.a", "pergunta": "Em caso positivo, informar dias, horários e carga horária mensal dedicados às atividades acima.", "tipo": "textarea", dependeDe: { id: "13", valor: "Sim" }},
      {"id": "14", "pergunta": "Participa de sociedade comercial ou ONG?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "15", "pergunta": "Participa de comissão ou grupo de trabalho?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "16", "pergunta": "Está respondendo cumulativamente por outro órgão?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "16.a", "pergunta": "A cumulação é voluntária ou involuntária?", "tipo": "radio", "opcoes": ["Voluntária", "Involuntária"], dependeDe: { id: "16", valor: "Sim" }},
      {"id": "16.b", "pergunta": "Especificar qual(is) órgão(s) está acumulando:", "tipo": "textarea", dependeDe: { id: "16", valor: "Sim" }},
      {"id": "17", "pergunta": "Nos últimos 12 meses afastou-se das atividades?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "17.a", "pergunta": "Especificar motivo e período.", "tipo": "textarea", dependeDe: { id: "17", valor: "Sim" }}
    ]
  },
  {
    "nome": "Dados da unidade",
    "campos":        [
        {"id": "18","pergunta": "O(a) membro(a) realiza atendimento ao público?","tipo": "radio","opcoes": ["Sim", "Não"]},
        {"id": "18.a","pergunta": "Em caso positivo, em qual modalidade:","tipo": "radio","opcoes": ["Presencial", "Virtual", "Ambos"],"dependeDe": { "id": "18", "valor": "Sim"}},
        {"id": "18.b","pergunta": "No caso de o(a) membro(a) realizar atendimento, especificar os dias da semana e horários:","tipo": "textarea","dependeDe": { "id": "18", "valor": "Sim" }},
        {"id": "18.c","pergunta": "Como o atendimento ao público do(a) membro(a) é registrado:", "tipo": "radio","opcoes": ["Sistemas de atuação (MPV e SAJ)", "Diretamente no RAF", "Outras formas"],"dependeDe": { "id": "18", "valor": "Sim" } },
        {"id": "18.d","pergunta": "Caso utilize outras formas de registro, especificar:","tipo": "textarea","dependeDe": { "id": "18.c", "valor": "Outras formas" } },
        {"id": "18.e","pergunta": "A equipe do órgão realiza atendimento ao público?","tipo": "radio","opcoes": ["Sim", "Não"]},
        {"id": "18.f", "pergunta": "Em caso positivo, em qual modalidade:", "tipo": "radio","opcoes": ["Presencial", "Virtual", "Ambos"],"dependeDe": { "id": "18.e", "valor": "Sim" }},
        {"id": "18.g", "pergunta": "No caso de a equipe realizar atendimento, especificar dias da semana e horários:","tipo": "textarea","dependeDe": { "id": "18.e", "valor": "Sim" }},
        {"id": "18.h","pergunta": "Como o atendimento ao público da equipe é registrado:","tipo": "radio","opcoes": ["Sistemas de atuação (MPV e SAJ)", "RAF do Membro", "Outras formas"], "dependeDe": { "id": "18.e", "valor": "Sim" }},
        {"id": "18.i","pergunta": "Caso utilize outras formas de registro, especificar:","tipo": "textarea", "dependeDe": { "id": "18.h", "valor": "Outras formas" }},

        {"id": "19", "pergunta": "Quantidade de servidores lotados no órgão correicionado.", "tipo": "number"},
        {"id": "20", "pergunta": "Especifique a quantidade acima relatada (dos servidores acima quantos são estagiários, cedidos, concursados, etc)", "tipo": "number"},
        {"id": "21", "pergunta": "Quantidade de terceirizados lotados no órgão correicionado.", "tipo": "number"},
        {"id": "22", "pergunta": "Quantidade de estagiários lotados no órgão correicionado.", "tipo": "number"},
        {"id": "23", "pergunta": "Os recursos humanos são adequados (quantidade), de acordo com o padrão de força de trabalho disponibilizada pelo Ministério Público local para órgãos semelhantes?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
        {"id": "23.a", "pergunta": "Em caso negativo, especificar.", "tipo": "textarea", dependeDe: { id: "23", valor: "Não" }},
        {"id": "24", "pergunta": "As instalações físicas são adequadas?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
        {"id": "24.a", "pergunta": "Especificar.", "tipo": "textarea", dependeDe: { id: "24", valor: "Não" }},
        {"id": "24.b", "pergunta": "O órgão funciona em prédio:", "tipo": "radio", "opcoes": ["Próprio", "Alugado", "Fórum da Comarca", "Outros"]},
        {"id": "24.c", "pergunta": "Em caso de outros, especificar.", "tipo": "textarea", dependeDe: { id: "24.b", valor: "Outros" }},
        {"id": "25", "pergunta": "Utiliza a rede institucional?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
        {"id": "25.a", "pergunta": "Em caso negativo, justificar.", "tipo": "textarea", dependeDe: { id: "25", valor: "Não" }},
        {"id": "25.b", "pergunta": "Utiliza o computador institucional?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
        {"id": "25.c", "pergunta": "Em caso negativo, justificar.", "tipo": "textarea", dependeDe: { id: "25.b", valor: "Não" }}
      ]
  },
{
    "nome": "Atuação geral",
    "campos": [
      {"id": "38", "pergunta": "O(a) membro(a) executa projetos pautados por objetivos estratégicos?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "38.a", "pergunta": "O(a) membro(a) possui projetos de iniciativa própria institucionalizados?", "tipo": "radio", "opcoes": ["Sim", "Não"], dependeDe: { id: "38", valor: "Sim" }},
      {"id": "38.b", "pergunta": "Em caso positivo, indicar o(s) projeto(s) executado(s) e o(s) respectivo(s) número(s) do(s) procedimento(s).", "tipo": "textarea", dependeDe: { id: "38", valor: "Sim" }},
      {"id": "38.c", "pergunta": "Dos projetos acima, quais os resultados concretos obtidos?", "tipo": "textarea", dependeDe: { id: "38", valor: "Sim" }},
      {"id": "38.d", "pergunta": "O(a) membro(a) aderiu a algum projeto institucional?","tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "38.e", "pergunta": "Em caso positivo, indicar o(s) projeto(s) executado(s) e o(s) respectivo(s) número(s) do(s) procedimento(s).", "tipo": "textarea", dependeDe: { id: "38.d", valor: "Sim" }},
      {"id": "38.f", "pergunta": "Dos projetos acima, quais os resultados concretos obtidos?", "tipo": "textarea", dependeDe: { id: "38.d", valor: "Sim" }},

      {"id": "39", "pergunta": "Utiliza indicadores sociais da sua área de atuação para tomada de decisão?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "39.a", "pergunta": "Especificar os indicadores utilizados.", "tipo": "textarea", dependeDe: { id: "39", valor: "Sim" }},
      {"id": "40", "pergunta": "Utiliza, em suas atividades, mecanismos de resolução consensual (negociação, mediação, conciliação, práticas restaurativas, convenções processuais, acordos de resultado), bem como outros métodos e mecanismos eficazes na resolução de conflitos, controvérsias e problemas?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "40.a", "pergunta": "Em caso positivo, indicar quais mecanismos utiliza e o número dos processos em que foram utilizados.", "tipo": "textarea", dependeDe: { id: "40", valor: "Sim" }},
      {"id": "41", "pergunta": "Possui Plano de Atuação?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "41.a", "pergunta": "Em caso positivo, foi realizado diagnóstico prévio das carências e necessidades sociais para a sua construção?", "tipo": "radio", "opcoes": ["Sim", "Não"], dependeDe: { id: "41", valor: "Sim" }},
      {"id": "42", "pergunta": "Que medidas adota para garantir a celeridade dos feitos (judiciais e extrajudiciais) sob sua responsabilidade?", "tipo": "textarea"},
      {"id": "43", "pergunta": "Prioriza a tutela coletiva, propondo ações individuais apenas quando absolutamente necessário?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "43.a", "pergunta": "Em caso afirmativo, exemplificar indicando número do(s) processo(s) em que houve prioridade da tutela coletiva.", "tipo": "textarea", dependeDe: { id: "43", valor: "Sim" }},
      {"id": "44", "pergunta": "Consegue identificar resultados objetivos decorrentes de sua atuação institucional?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "44.a", "pergunta": "Em caso afirmativo, explicar quais são esses resultados.", "tipo": "textarea", dependeDe: { id: "44", valor: "Sim" }},
      {"id": "45", "pergunta": "No exercício de sua atividade, há atuação com perspectiva de gênero?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "45.a", "pergunta": "Em caso afirmativo, especificar.", "tipo": "textarea", dependeDe: { id: "45", valor: "Sim" }}
      
    ]
  },
   
  {
    "nome": "Dados específicos",
    "subtopicos": [
      { "id":"sub27", "nome":"infância e juventude",              "prefixo":"27" , "titulo":"INFÂNCIA E JUVENTUDE" },
     
      { "id":"sub29", "nome":"educação",              "prefixo":"29" , "titulo":"EDUCAÇÃO" },
      { "id":"sub31", "nome":"FAMÍLIA",              "prefixo":"31" , "titulo":"FAMÍLIA" },
      { "id":"sub32", "nome":"VIOLENCIA DOMÉSTICA",        "prefixo":"32" , "titulo":"VIOLENCIA DOMÉSTICA" },
      { "id":"sub33", "nome":"DISCRIMINAÇÃO",          "prefixo":"33" , "titulo":"DISCRIMINAÇÃO" },
      { "id":"sub37", "nome":"MEIO AMBIENTE",          "prefixo":"37" , "titulo":"MEIO AMBIENTE" },
      { "id":"sub36", "nome":"PATRIMÔNIO PÚBLICO",     "prefixo":"36" , "titulo":"PATRIMÔNIO PÚBLICO" },
      { "id":"sub34", "nome":"ATUAÇÃO NA DEFESA DAS PESSOAS COM DEFICIÊNCIA/IDOSO",   "prefixo":"34" , "titulo":"ATUAÇÃO NA DEFESA DAS PESSOAS COM DEFICIÊNCIA/IDOSO" },
       
      { "id":"sub35", "nome":"Execução penal, controle externo da atividade policial e segurança pública",      "prefixo":"35" , "titulo":"EXECUÇÃO PENAL, CONTROLE EXTERNO DA ATIVIDADE POLICIAL E SEGURANÇA PÚBLICA" },
      { "id":"sub30", "nome":"saúde",              "prefixo":"30" , "titulo":"SAÚDE" },
      { "id":"sub28", "nome":"crimes contra crianças e adolescentes",              "prefixo":"28", "titulo":"CRIMES CONTRA CRIANÇAS E ADOLESCENTES"  }
    ],
    "campos": [
      {"id": "27.a", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "27.b", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "27.c", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "27.d", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "27.e", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "27.f", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "27.g", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "27.h", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "27.i", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "27.j", "pergunta": "Audiências públicas", "tipo": "number"},
        {"id": "27.k", "pergunta": "Audiências judiciais", "tipo": "number"},
        { "id": "27.l", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "27.m", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "27.n", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "27.o", "pergunta": "Visitas em estabelecimentos de acolhimento institucional de crianças e adolescentes", "tipo": "number" },
        { "id": "27.p", "pergunta": "Visitas em instituições de medidas socioeducativas em meio aberto", "tipo": "number" },
        { "id": "27.q", "pergunta": "Visitas em instituições de medidas socioeducativas de internação e semiliberdade", "tipo": "number" },
        { "id": "27.r", "pergunta": "Outras visitas/inspeções", "tipo": "number" },

        
        {"id": "28.a", "pergunta": "Inquéritos Policiais recebidos", "tipo": "number"},
        {"id": "28.b", "pergunta": "Termos Circunstanciados de Ocorrência recebidos", "tipo": "number"},
        {"id": "28.c", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "28.d", "pergunta": "Procedimentos Investigatórios Criminais instaurados", "tipo": "number"},
        {"id": "28.e", "pergunta": "Processos criminais recebidos", "tipo": "number"},
        {"id": "28.f", "pergunta": "Acordos de Não Persecução Penal (ANPP)", "tipo": "number"},
        {"id": "28.g", "pergunta": "Audiências judiciais", "tipo": "number"},
        { "id": "28.h", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "28.i", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "28.j", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "28.k", "pergunta": "Outras visitas/inspeções", "tipo": "number" },
       
       
        {"id": "29.a", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "29.b", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "29.c", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "29.d", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "29.e", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "29.f", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "29.g", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "29.h", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "29.i", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "29.j", "pergunta": "Audiências públicas", "tipo": "number"},
        { "id": "29.k", "pergunta": "Audiências judiciais", "tipo": "number" },
        { "id": "29.l", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "29.m", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "29.n", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "29.o", "pergunta": "Inspeções/Visitas", "tipo": "number" },
 
       
        {"id": "30.a", "pergunta": "Inquéritos Policiais recebidos", "tipo": "number"},
        {"id": "30.b", "pergunta": "Termos Circunstanciados de Ocorrência recebidos", "tipo": "number"},
        {"id": "30.c", "pergunta": "Procedimentos Investigatórios Criminais instaurados", "tipo": "number"},
        {"id": "30.d", "pergunta": "Processos criminais recebidos", "tipo": "number"},
        {"id": "30.e", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "30.f", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "30.g", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "30.h", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "30.i", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "30.j", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "30.k", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "30.l", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "30.m", "pergunta": "Acordos de Não Persecução Penal (ANPP)", "tipo": "number"},
        {"id": "30.n", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "30.o", "pergunta": "Audiências públicas", "tipo": "number"},
        {"id": "30.p", "pergunta": "Audiências judiciais", "tipo": "number"},
        { "id": "30.q", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "30.r", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "30.s", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "30.t", "pergunta": "Inspeções/Visitas", "tipo": "number" },

      
      
        {"id": "31.a", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "31.b", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "31.c", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "31.d", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "31.e", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "31.f", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "31.g", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "31.h", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "31.i", "pergunta": "Audiências judiciais", "tipo": "number"},
        { "id": "31.j", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "31.k", "pergunta": "Inspeções/Visitas", "tipo": "number" },

        
        
        {"id": "32.a", "pergunta": "Inquéritos Policiais recebidos", "tipo": "number"},
        {"id": "32.b", "pergunta": "Termos Circunstanciados de Ocorrência recebidos", "tipo": "number"},
        {"id": "32.c", "pergunta": "Procedimentos Investigatórios Criminais instaurados", "tipo": "number"},
        {"id": "32.d", "pergunta": "Processos criminais recebidos", "tipo": "number"},
        {"id": "32.e", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "32.f", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "32.g", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "32.h", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "32.i", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "32.j", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "32.k", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "32.l", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "32.m", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "32.n", "pergunta": "Audiências públicas", "tipo": "number"},
        {"id": "32.o", "pergunta": "Audiências judiciais", "tipo": "number"},
        { "id": "32.p", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "32.q", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "32.r", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "32.s", "pergunta": "Inspeções/Visitas", "tipo": "number" },

        
        
        {"id": "33.a", "pergunta": "Inquéritos Policiais recebidos", "tipo": "number"},
        {"id": "33.b", "pergunta": "Termos Circunstanciados de Ocorrência recebidos", "tipo": "number"},
        {"id": "33.c", "pergunta": "Procedimentos Investigatórios Criminais instaurados", "tipo": "number"},
        {"id": "33.d", "pergunta": "Processos criminais recebidos", "tipo": "number"},
        {"id": "33.e", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "33.f", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "33.g", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "33.h", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "33.i", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "33.j", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "33.k", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "33.l", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "33.m", "pergunta": "Acordos de Não Persecução Penal (ANPP)", "tipo": "number"},
        {"id": "33.n", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "33.o", "pergunta": "Audiências públicas", "tipo": "number"},
        {"id": "33.p", "pergunta": "Audiências judiciais", "tipo": "number"},
        {"id": "33.q", "pergunta": "Inspeções/Visitas", "tipo": "number"},
        { "id": "33.q", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "33.r", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "33.s", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "33.t", "pergunta": "Inspeções/Visitas", "tipo": "number" },

        
        {"id": "34.a", "pergunta": "Inquéritos Policiais recebidos", "tipo": "number"},
        {"id": "34.b", "pergunta": "Termos Circunstanciados de Ocorrência recebidos", "tipo": "number"},
        {"id": "34.c", "pergunta": "Procedimentos Investigatórios Criminais instaurados", "tipo": "number"},
        {"id": "34.d", "pergunta": "Processos criminais recebidos", "tipo": "number"},
        {"id": "34.e", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "34.f", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "34.g", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "34.h", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "34.i", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "34.j", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "34.k", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "34.l", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "34.m", "pergunta": "Acordos de Não Persecução Penal (ANPP)", "tipo": "number"},
        {"id": "34.n", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "34.o", "pergunta": "Audiências públicas", "tipo": "number"},
        {"id": "34.p", "pergunta": "Audiências judiciais", "tipo": "number"},
        { "id": "34.q", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "34.r", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "34.s", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "34.t", "pergunta": "Visitas em instituições de longa permanência e serviços de proteção a idosos", "tipo": "number" },
        { "id": "34.u", "pergunta": "Outras inspeções/visitas", "tipo": "number" },

       
       
        {"id": "35.a", "pergunta": "Inquéritos Policiais recebidos", "tipo": "number"},
        {"id": "35.b", "pergunta": "Termos Circunstanciados de Ocorrência recebidos", "tipo": "number"},
        {"id": "35.c", "pergunta": "Procedimentos Investigatórios Criminais instaurados conforme Resolução nº 310/2025 do CNMP.", "tipo": "number"},
        {"id": "35.d", "pergunta": "Processos criminais recebidos", "tipo": "number"},
        {"id": "35.e", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "35.f", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "35.g", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "35.h", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "35.i", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "35.j", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "35.k", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "35.l", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "35.m", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "35.n", "pergunta": "Audiências públicas", "tipo": "number"},
        {"id": "35.o", "pergunta": "Audiências judiciais", "tipo": "number"},
        {"id": "35.p", "pergunta": "Sentenças Desfavoráveis", "tipo": "number"},
        { "id": "35.q", "pergunta": "Recursos interpostos", "tipo": "number" },
        { "id": "35.r", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "35.s", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "35.t", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "35.u", "pergunta": "Visitas em estabelecimentos prisionais", "tipo": "number" },
        { "id": "35.v", "pergunta": "Visitas em delegacias estaduais, unidades de medicina legal e unidades de perícia criminal", "tipo": "number" },
        { "id": "35.w", "pergunta": "Visitas em estabelecimentos militares", "tipo": "number" },
        { "id": "35.x", "pergunta": "Outras inspeções/visitas", "tipo": "number" },

        
        
        {"id": "36.a", "pergunta": "Inquéritos Policiais recebidos", "tipo": "number"},
        {"id": "36.b", "pergunta": "Termos Circunstanciados de Ocorrência recebidos", "tipo": "number"},
        {"id": "36.c", "pergunta": "Procedimentos Investigatórios Criminais instaurados", "tipo": "number"},
        {"id": "36.d", "pergunta": "Processos criminais recebidos", "tipo": "number"},
        {"id": "36.e", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "36.f", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "36.g", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "36.h", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "36.i", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "36.j", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "36.k", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "36.l", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "36.m", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "36.n", "pergunta": "Audiências públicas", "tipo": "number"},
        {"id": "36.o", "pergunta": "Audiências judiciais", "tipo": "number"},
        { "id": "36.p", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "36.q", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "36.r", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "36.s", "pergunta": "Inspeções/Visitas", "tipo": "number" },

        
        
        {"id": "37.a", "pergunta": "Inquéritos Policiais recebidos", "tipo": "number"},
        {"id": "37.b", "pergunta": "Termos Circunstanciados de Ocorrência recebidos", "tipo": "number"},
        {"id": "37.c", "pergunta": "Procedimentos Investigatórios Criminais instaurados", "tipo": "number"},
        {"id": "37.d", "pergunta": "Processos criminais recebidos", "tipo": "number"},
        {"id": "37.e", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "37.f", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "37.g", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "37.h", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "37.i", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "37.j", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "37.k", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "37.l", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "37.m", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "37.n", "pergunta": "Audiências públicas", "tipo": "number"},
        {"id": "37.o", "pergunta": "Audiências judiciais", "tipo": "number"},
        {"id": "37.p", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        { "id": "37.q", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        { "id": "37.r", "pergunta": "Ações de Improbidade", "tipo": "number" },
        { "id": "37.s", "pergunta": "Inspeções/Visitas", "tipo": "number" }

    ]
  },
 {
    "nome": "Dados estatísticos gerais do órgão",

    "campos": [
        {"id": "26.a", "pergunta": "Inquéritos Policiais recebidos", "tipo": "number","obrigatorio": false},
        {"id": "26.b", "pergunta": "Termos Circunstanciados de Ocorrência recebidos", "tipo": "number"},
        {"id": "26.c", "pergunta": "Procedimentos Investigatórios Criminais instaurados", "tipo": "number"},
        {"id": "26.d", "pergunta": "Processos criminais recebidos", "tipo": "number"},
        {"id": "26.e", "pergunta": "Processos cíveis recebidos", "tipo": "number"},
        {"id": "26.f", "pergunta": "Notícias de Fato (NF) autuadas", "tipo": "number"},
        {"id": "26.g", "pergunta": "Inquéritos Civis (IC) instaurados", "tipo": "number"},
        {"id": "26.h", "pergunta": "Procedimentos Preparatórios (PP) instaurados", "tipo": "number"},
        {"id": "26.i", "pergunta": "Procedimentos Administrativos (PA) instaurados", "tipo": "number"},
        {"id": "26.j", "pergunta": "Recomendações", "tipo": "number"},
        {"id": "26.k", "pergunta": "Termos de Ajustamento de Conduta (TAC)", "tipo": "number"},
        {"id": "26.l", "pergunta": "Acordos de Não Persecução Cível (ANPC)", "tipo": "number"},
        {"id": "26.m", "pergunta": "Acordos de Não Persecução Penal (ANPP)", "tipo": "number"},
        {"id": "26.n", "pergunta": "Reuniões", "tipo": "number"},
        {"id": "26.o", "pergunta": "Audiências públicas", "tipo": "number"},
        {"id": "26.p", "pergunta": "Audiências judiciais", "tipo": "number" },
        {"id": "26.r", "pergunta": "Audiências extrajudiciais", "tipo": "number" },
        {"id": "26.s", "pergunta": "Ações Civis Públicas", "tipo": "number" },
        {"id": "26.t", "pergunta": "Ações de Improbidade", "tipo": "number" },
        {"id": "26.q", "pergunta": "Visitas em instituições de longa permanência e serviços de proteção a idosos", "tipo": "number" },
        {"id": "26.u", "pergunta": "Visitas em instituições de medidas socioeducativas em meio aberto", "tipo": "number" },
        {"id": "26.v", "pergunta": "Visitas em instituições de medidas socioeducativas de internação e semiliberdade", "tipo": "number" },
        {"id": "26.w", "pergunta": "Visitas em estabelecimentos de acolhimento institucional de crianças e adolescentes", "tipo": "number" },
        {"id": "26.x", "pergunta": "Visitas em estabelecimentos prisionais", "tipo": "number" },
        {"id": "26.y", "pergunta": "Visitas em delegacias estaduais, unidades de medicina legal e unidades de perícia criminal", "tipo": "number" },
        {"id": "26.z", "pergunta": "Visitas em estabelecimentos militares", "tipo": "number" },
        {"id": "26.aa", "pergunta": "Outras visitas/inspeções", "tipo": "number" }

      ]
  },

  
  {
    "nome": "Resolutiva e de relevância social",
    "campos": [
    {"id":"47","pergunta":"O(a) membro(a) realizou audiência pública como proponente nos últimos 12 meses?","tipo":"radio","opcoes":["Sim","Não"]},
    {"id":"47.a","pergunta":"Em caso positivo, informar a temática e o número do procedimento.","tipo":"textarea","dependeDe":{"id":"47","valor":"Sim"}},
    {"id":"47.b","pergunta":"O(a) membro(a) participou audiência pública como convidado nos últimos 12 meses?","tipo":"radio","opcoes":["Sim","Não"]},
    {"id":"47.c","pergunta":"Em caso positivo, informar a temática e o número do procedimento (se houver).","tipo":"textarea","dependeDe":{"id":"47.b","valor":"Sim"}},
    {"id":"48","pergunta":"O(a) membro(a) realizou palestras vinculadas às políticas públicas de sua respectiva área de atuação ministerial?","tipo":"radio","opcoes":["Sim","Não"]},
    {"id":"48.a","pergunta":"Em caso positivo, informar a temática e o número do procedimento.","tipo":"textarea","dependeDe":{"id":"48","valor":"Sim"}},
    {"id":"48.b","pergunta":"O(a) membro(a) realizou ou participou de reuniões, com agentes externos(as), vinculadas às políticas públicas das respectivas áreas de atuação ministerial?","tipo":"radio","opcoes":["Sim","Não"]},
    {"id":"48.c","pergunta":"Em caso positivo, informar a temática e o número do procedimento.","tipo":"textarea","dependeDe":{"id":"48.b","valor":"Sim"}},
    {"id":"49","pergunta":"O(a) membro(a) realizou atividades não procedimentais de relevância social, tais como palestras, participação em reuniões e outras atividades que resultem em medidas de inserção social, especialmente por meio de projetos sociais?","tipo":"radio","opcoes":["Sim","Não"]},
    {"id":"49.a","pergunta":"Em caso positivo, especificar as atividades realizadas e a temática.","tipo":"textarea","dependeDe":{"id":"49","valor":"Sim"}},
    {"id":"50","pergunta":"O(a) membro(a) fez utilização eficiente e/ou viabilizou a priorização de mecanismos de resolução consensual e extrajurisdicional de conflitos, controvérsias e problemas?","tipo":"radio","opcoes":["Sim","Não"]},
    {"id":"50.a","pergunta":"Em caso positivo, especificar.","tipo":"textarea","dependeDe":{"id":"50","valor":"Sim"}},
    {"id":"51","pergunta":"Nas ACPs propostas nos últimos 12 meses, foi priorizada a utilização eficiente e/ou viabilidade de priorização de mecanismos de resolução consensual e extrajurisdicional de conflitos, controvérsias e problemas?","tipo":"radio","opcoes":["Sim","Não"]},
    {"id":"51.a","pergunta":"Em caso positivo, especificar.","tipo":"textarea","dependeDe":{"id":"51","valor":"Sim"}},
    {"id":"52","pergunta":"Foi feita utilização eficiente e objetiva de instrumentos e métodos de investigação na determinação de diligências, bem como dos recursos extrajudiciais e judiciais visando à prevenção e à tempestiva correção de ilícitos?","tipo":"radio","opcoes":["Sim","Não"]},
    {"id":"52.a","pergunta":"Em caso positivo, especificar.","tipo":"textarea","dependeDe":{"id":"52","valor":"Sim"}},
    {"id":"53","pergunta":"Cite as atuações nos casos que envolveram desconformidades complexas e que demandaram reestruturação de políticas públicas, especialmente quando violadoras de direitos fundamentais e de grande impacto social. (a identificação do problema como estrutural deve obedecer às diretrizes estabelecidas na Recomendação de Caráter Geral CNMP/CN nº 5 de 06 de março de 2025.","tipo":"textarea"}

    ]
  },{
   "nome": "Dados Específicos por Área",
    "subtopicos": [
      { "id":"sub50", "nome":"INFÂNCIA E JUVENTUDE CÍVEL",   "prefixo": ["54","55","56","57","58","59","60","61","62","63", "64","65","66","67","68","69"], "titulo":"INFÂNCIA E JUVENTUDE CÍVEL" },
      { "id":"sub32", "nome":"CRIMES CONTRA CRIANÇAS E ADOLESCENTES" ,   "prefixo":["70","71","72"], "titulo":"CRIMES CONTRA CRIANÇAS E ADOLESCENTES" },
      { "id":"sub33", "nome": "Educação",    "prefixo": ["73","74","75","76","77","78","79","80","81","82","83","84"] , "titulo":"EDUCAÇÃO" },
      { "id":"sub34", "nome":"família",  "prefixo": ["85","86","87","88","89","90"], "titulo":"FAMÍLIA" },
      { "id":"sub35", "nome":"VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER",      "prefixo": ["91","92","93","94","95","96","97","98","99","100"] , "titulo":"VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER" },
      { "id":"sub36", "nome":"Combate à Discriminação",     "prefixo": ["101","102","103","104","105","106","107"] , "titulo":"ENFRENTAMENTO À DISCRIMINAÇÃO RACIAL, À POPULAÇÃO LGBTQIAPN+ E AOS POVOS E COMUNIDADES TRADICIONAIS" },
      { "id":"sub37", "nome":"Pessoas com Deficiência",          "prefixo": ["108","109","110","111","112","113"], "titulo":"PESSOAS COM DEFICIÊNCIA" },
      { "id":"sub38", "nome":"Segurança Pública e execução Penal",          "prefixo": ["114","115","116","117","118","119"], "titulo":"EXECUÇÃO PENAL, CONTROLE EXTERNO DA ATIVIDADE POLICIAL E SEGURANÇA PÚBLICA" },
      { "id":"sub37", "nome":"Probidade e Acesso à Informação",          "prefixo": ["120","121","122"], "titulo":"PATRIMÔNIO PÚBLICO, PROBIDADE ADMINISTRATIVA E ACESSO À INFORMAÇÃO" },
      { "id":"sub37", "nome":"Saúde",          "prefixo": ["123","124","125","126","127","128","129","130","131","132"], "titulo":"SAÚDE" },
      { "id":"sub37", "nome":"Meio Ambiente",       "prefixo": ["133","134","135","136"], "titulo":"MEIO AMBIENTE" },
        ],
    "campos": [
      
      {"id":"54","pergunta":"O(a) membro(a) realiza ou participa de Reuniões periódicas com a rede para discussão de casos ou para implementação de políticas públicas na área da infância e juventude, com construção de fluxos e protocolos, atuando extrajudicialmente para garantir o pleno funcionamento da rede de proteção à criança e ao adolescente, conforme o artigo 4º da Recomendação nº 33/2016?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"54.a","pergunta":"Em caso afirmativo, especificar, inclusive, a periodicidade dos encontros.","tipo":"textarea","dependeDe":{"id":"54","valor":"Sim"}},
      {"id":"55","pergunta":"Há serviço de acolhimento institucional na comarca?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"55.a","pergunta":"Em caso positivo, descrever como o(a) membro(a) tem fiscalizado e atuado para qualificar o serviço, conforme a Resolução CNMP nº 293/2024.","tipo":"textarea","dependeDe":{"id":"55","valor":"Sim"}},
      {"id":"56","pergunta":"Há serviço de acolhimento familiar no(s) município(s) em que atua?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"56.a","pergunta":"Em caso negativo, quais medidas estão sendo adotadas para sua implementação, consoante o artigo 12 da Resolução CNMP nº 293/2024?","tipo":"textarea","dependeDe":{"id":"56","valor":"Não"}},
      {"id":"56.b","pergunta":"Informar o número do processo judicial ou extrajudicial, caso existente.","tipo":"text","dependeDe":{"id":"56","valor":"Não"}},
      {"id":"57","pergunta":"O(a) membro(a) efetua, em caráter permanente, nos termos do artigo 13 da Resolução CNMP nº 293/2024, a verificação do Sistema Nacional de Adoção e Acolhimento (SNA), com login e senha próprios, garantindo que o sistema retrate com exatidão a situação das crianças e adolescentes acolhidos e observando a ordem de convocação dos habilitados à adoção?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"57.a","pergunta":"De que forma realiza essa verificação?","tipo":"textarea","dependeDe":{"id":"57","valor":"Sim"}},
      {"id":"58","pergunta":"O(a) membro(a) adota as medidas cabíveis para garantir o direito à convivência familiar das crianças e adolescentes acolhidos, zelando prioritariamente pela reintegração familiar, quando cabível, ou pela colocação em família substituta? (Conforme o artigo 7º da Resolução CNMP nº 293/2024, observando o prazo de 15 dias, contados da data de recebimento do relatório da equipe técnica, para o ajuizamento da ação de destituição do poder familiar.)","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"58.a","pergunta":"Especificar.","tipo":"textarea","dependeDe":{"id":"58","valor":"Sim"}},
      {"id":"59","pergunta":"Havendo criança ou adolescente acolhido há mais de 18 (dezoito) meses, o(a) membro(a) tem zelado para que o serviço de acolhimento adote as medidas necessárias à garantia da convivência familiar e comunitária, conforme o artigo 10 da Resolução CNMP nº 293/2024?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"59.a","pergunta":"Especificar.","tipo":"textarea","dependeDe":{"id":"59","valor":"Sim"}},
      {"id":"60","pergunta":"Há crianças ou adolescentes acolhidos provenientes de outra comarca ou município?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"60.a","pergunta":"Em caso positivo, o(a) membro(a) tem adotado as medidas previstas no art. 7º, § 2º, da Resolução CNMP nº 293/2024?","tipo":"radio","opcoes":["Sim","Não"],"dependeDe":{"id":"60","valor":"Sim"}},
      {"id":"60.b","pergunta":"Especificar as medidas adotadas.","tipo":"textarea","dependeDe":{"id":"60","valor":"Sim"}},
      {"id":"61","pergunta":"O(a) membro(a) realiza a oitiva informal prevista no artigo 179 do ECA?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"62","pergunta":"Existe fluxo estabelecido com a Delegacia de Polícia, Poder Judiciário, Defensoria Pública e Assistência Social para agilizar o atendimento inicial ao adolescente a quem se atribua autoria de ato infracional, nos termos do artigo 88, V, do ECA?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"62.a","pergunta":"Especificar.","tipo":"textarea","dependeDe":{"id":"62","valor":"Sim"}},
      {"id":"63","pergunta":"Há unidade de internação ou de semiliberdade na comarca?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"63.a","pergunta":"Em caso positivo, descrever como o(a) membro(a) tem fiscalizado e atuado para qualificar o serviço, conforme a Resolução CNMP nº 67/2011.","tipo":"textarea","dependeDe":{"id":"63","valor":"Sim"}},
      {"id":"63.b","pergunta":"Em caso negativo, há procedimento instaurado?","tipo":"radio","opcoes":["Sim","Não"],"dependeDe":{"id":"63","valor":"Não"}},
      {"id":"63.c","pergunta":"Em caso positivo, especificar.","tipo":"textarea","dependeDe":{"id":"63.b","valor":"Sim"}},
      {"id":"64","pergunta":"Quanto ao meio aberto, foram adotadas medidas administrativas ou judiciais voltadas à criação e manutenção dos programas de atendimento socioeducativo dos municípios que integram a comarca, conforme o artigo 4º da Resolução CNMP nº 204/2019?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"64.a","pergunta":"Em caso positivo, especificar.","tipo":"textarea","dependeDe":{"id":"64","valor":"Sim"}},
      {"id":"65","pergunta":"No município onde atua, foram adotadas medidas administrativas ou judiciais voltadas à implementação do Plano Municipal da Primeira Infância, com ampla discussão com a sociedade e com o Conselho Municipal dos Direitos da Criança e do Adolescente? (Conforme o artigo 7º da Lei nº 13.257/2016.)","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"65.a","pergunta":"Em caso positivo, especificar.","tipo":"textarea","dependeDe":{"id":"65","valor":"Sim"}},
      {"id":"66","pergunta":"Foram adotadas medidas administrativas ou judiciais voltadas à permanente fiscalização do Fundo Municipal (ou Estadual, havendo atribuição) para Infância e Adolescência (FIA), conforme disposto no artigo 260, § 4º, do ECA, zelando para que os recursos por estes captados sejam utilizados de acordo com as prioridades estabelecidas pelo Conselho Municipal (ou Estadual, havendo atribuição) de Direitos da Criança e do Adolescente local, conforme o artigo 4º, VI, da Recomendação CNMP nº 33/2016?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"66.a","pergunta":"Em caso positivo, especificar.","tipo":"textarea","dependeDe":{"id":"66","valor":"Sim"}},
      {"id":"67","pergunta":"Foram adotadas medidas para implementação, no(s) município(s) em que atua, do sistema de garantia de direitos da criança e do adolescente vítima ou testemunha de violência e do fluxo/protocolo da escuta especializada, conforme a Lei nº 13.431/2017, o Decreto nº 9.603/2018, e o artigo 3º da Resolução CNMP nº 287/2024?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"68","pergunta":"Há articulação ou atuação integrada entre as Promotorias de Justiça criminais, de violência doméstica e familiar, de família e da infância e juventude, nos termos do art. 2º da Resolução CNMP nº 287/2024?","tipo":"radio","opcoes":["Sim","Não"]},
      {"id":"68.a","pergunta":"Especifique com qual(is) Promotoria(s) de Justiça realiza atuação integrada ou, caso inexistente, justifique a ausência dessa articulação.","tipo":"textarea"},

      {"id":"69","pergunta":"No caso de realização de depoimento especial, ele é emprestado aos demais juízos quando necessário?","tipo":"radio","opcoes":["Sim","Não"]},



      {"id": "70", "pergunta": "Há atuação para garantir a implementação local da política pública de enfrentamento à violência contra crianças e adolescentes vítima ou testemunha de violência, nos termos do artigo 3º da Resolução CNMP n. 287/2024?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "70.a", "pergunta": "Especificar.", "tipo": "textarea", dependeDe: { id: "70", valor: "Sim" }},
      {"id": "71", "pergunta": "Como tem sido o fluxo para o depoimento especial na comarca?", "tipo": "textarea"},
      {"id": "71.a", "pergunta": "Há utilização desta prova como prova emprestada nos outros juízos?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "71.b", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "71.a", valor: "Sim" }},
      {"id": "72", "pergunta": "Há alguma articulação ou atuação integrada entre as Promotorias de Justiça criminais, as Promotorias de Justiça de violência doméstica e familiar, as Promotorias de Justiça de família e as Promotorias de Justiça da infância e juventude, nos termos do art. 2º da Resolução CNMP nº 287/2024?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "72.a", "pergunta": "Especifique com qual(is) Promotoria(s) de Justiça realiza atuação integrada ou, caso inexistente, justifique a ausência dessa articulação.", "tipo": "textarea", dependeDe: { id: "72", valor: "Sim" }},
    
      {"id": "73", "pergunta": "Foram adotadas medidas administrativas ou judiciais voltadas ao aumento da oferta de vagas em creches públicas?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "73.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "73", valor: "Sim" }},
      {"id": "74", "pergunta": "O(a) membro(a) adotou medidas administrativas ou judiciais voltadas à garantia da universalização da pré-escola, obrigatória para crianças de 4 a 5 anos?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "74.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "74", valor: "Sim" }},
      {"id": "75", "pergunta": "O(a) membro(a) adotou medidas voltadas ao fomento da oferta do atendimento educacional especializado a crianças com deficiência, transtornos globais do desenvolvimento e altas habilidades?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "75.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "75", valor: "Sim" }},
      {"id": "76", "pergunta": "Foram adotadas medidas voltadas ao acompanhamento do processo de elaboração das leis orçamentárias do município, para assegurar dotações compatíveis com as metas do Plano Nacional de Educação?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "76.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "76", valor: "Sim" }},
      {"id": "77", "pergunta": "Foram adotadas medidas voltadas à garantia da infraestrutura mínima adequada em escolas ou centros de educação infantil?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "77.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "77", valor: "Sim" }},
      {"id": "78", "pergunta": "Há atuação específica sobre eventual retomada de obras paralisadas da educação, nos termos da Lei nº 14.719/2023?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "78.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "78", valor: "Sim" }},
      {"id": "79", "pergunta": "Foram adotadas medidas voltadas à expansão do tempo integral conforme a Meta do Plano Nacional de Educação?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "79.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "79", valor: "Sim" }},
      {"id": "80", "pergunta": "Foram adotadas medidas voltadas à defesa da gestão democrática do ensino, conforme Meta do Plano Nacional de Educação?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "80.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "80", valor: "Sim" }},
      {"id": "81", "pergunta": "Foram adotadas medidas voltadas à valorização dos(as) profissionais da educação, conforme Meta do Plano Nacional de Educação?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "81.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "81", valor: "Sim" }},
      {"id": "82", "pergunta": "O(a) membro(a) acompanha as estratégias adotadas pela Secretaria Municipal de Educação e pelo Conselho Tutelar para combater a evasão e o abandono escolar.", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "82.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "82", valor: "Sim" }},
      {"id": "83", "pergunta": "O(a) membro(a) atua na Educação de Jovens e Adultos (EJA) com foco na defesa do direito constitucional à educação.", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "83.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo.", "tipo": "textarea", dependeDe: { id: "83", valor: "Sim" }},
      {"id": "84", "pergunta": "O(a) membro(a) tem atuação voltada ao enfrentamento ao analfabetismo?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "84.a", "pergunta": "Em caso positivo, especificar e informar o número do procedimento/processo, caso existente.", "tipo": "textarea", dependeDe: { id: "84", valor: "Sim" }},
      {"id": "85", "pergunta": "Em procedimentos que envolvem guarda compartilhada, o(a) membro(a) analisa, no caso concreto, se a mulher é vítima de violência doméstica, na forma do artigo 1.584, § 2º, do Código Civil (alterado pela Lei nº 14.713/2023)?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "85.a", "pergunta": "Em caso positivo, informar o número do processo como exemplo de atuação.", "tipo": "textarea", dependeDe: { id: "85", valor: "Sim" }},
      {"id": "86", "pergunta": "O(a) membro(a) atua em todos os processos judiciais de família em que a mulher é vítima de violência doméstica, conforme determina o artigo 698, parágrafo único, do CPC (incluído pela Lei nº 13.894/2019)?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "86.a", "pergunta": "Em caso positivo, informar o número do processo como exemplo de atuação.", "tipo": "textarea", dependeDe: { id: "86", valor: "Sim" }},
      {"id": "87", "pergunta": "O(a) membro(a) atua em todos os processos judiciais que envolvam direitos de crianças e adolescentes, de incapazes ou de idosos em situação de vulnerabilidade, nos termos do artigo 5º, VIII, da Recomendação CNMP nº 34/2016?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "88", "pergunta": "Especifique com qual(is) Promotoria(s) de Justiça realiza atuação integrada ou, caso inexistente, justifique a ausência dessa articulação. ", "tipo": "textarea"},
      {"id": "88.a", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "88", valor: "Sim" }},
      {"id": "89", "pergunta": "Em situações de crianças e adolescentes vítimas de violência, O(a) membro(a) zela para que o depoimento especial ocorra preferencialmente no âmbito criminal, com posterior compartilhamento de provas com a Promotoria de Justiça da área de família, nos termos do artigo 8º da Resolução CNMP nº 287/2024?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "90", "pergunta": "Nos casos de alienação parental que não tenham repercussão criminal, O(a) membro(a) zela para que, havendo necessidade de oitiva da criança ou do adolescente, esta seja realizada obrigatoriamente por meio de depoimento especial, conforme o artigo 8-A da Lei nº 12.318/2010?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "91", "pergunta": "O(a) membro(a) fomenta o diálogo entre as polícias civil e militar e as redes de saúde e assistência social, por meio de encontros temáticos, cursos de formação e outras atividades, com o objetivo de promover a proteção integral à mulher?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "91.a", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "91", valor: "Sim" }},
      {"id": "92", "pergunta": "O(a) membro(a) analisa o histórico de violência doméstica ou familiar sofrida pela vítima, a fim de instruir o processo criminal?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "93", "pergunta": "Há o regular preenchimento do Cadastro Nacional de Violência Doméstica do CNMP?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "94", "pergunta": "O(a) membro(a) tem fiscalizado se a Polícia Civil aplica o Formulário Nacional de Avaliação de Risco (FONAR) em todos os casos que envolvam violência doméstica no âmbito familiar?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "94.a", "pergunta": "O(a) membro(a) atua na fiscalização e no fomento do cumprimento das medidas protetivas de urgência com absoluta prioridade, nos termos da Recomendação CNMP nº 87/2021?", "tipo": "textarea"},
      {"id": "95", "pergunta": "Existe delegacia especializada?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "95.a", "pergunta": "Em caso negativo, tem policial feminina compondo a equipe da Delegacia e de que forma é realizado o acolhimento da mulher vítima de violência?", "tipo": "textarea", dependeDe: { id: "95", valor: "Não" }},
     
      {"id": "96", "pergunta": "Há monitoramento dos indicadores locais relativos à violência doméstica e familiar contra a mulher?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "96.a", "pergunta": "Especificar.", "tipo": "textarea", dependeDe: { id: "96", valor: "Sim" }},
     {"id": "96.b", "pergunta": "O(a) membro(a) desenvolve atuação integrada com a Promotoria de Justiça com atribuição em feminicídio a fim de desenvolverem ações preventivas?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "96.c", "pergunta": "Especifique com qual(is) Promotoria(s) de Justiça realiza atuação integrada ou, caso inexistente, justifique a ausência dessa articulação.", "tipo": "textarea"},

      {"id": "96.d", "pergunta": "O(a) membro(a) realiza atuação integrada com as Promotorias de Justiça com atribuição nos crimes contra crianças e adolescentes a fim de desenvolverem ações preventivas?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "96.e", "pergunta": "Especifique com qual(is) Promotoria(s) de Justiça realiza atuação integrada ou, caso inexistente, justifique a ausência dessa articulação.", "tipo": "textarea"},

      {"id": "96.f", "pergunta": "O(a) membro(a) realiza atuação integrada com as Promotorias de Justiça com atribuição em direito de família para que, nas causas cíveis relacionadas a um contexto de violência doméstica contra a mulher, ocorra a intervenção obrigatória do Ministério Público, em razão da vulnerabilidade presumida da mulher?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "96.g", "pergunta": "Especifique com qual(is) Promotoria(s) de Justiça realiza atuação integrada ou, caso inexistente, justifique a ausência dessa articulação.", "tipo": "textarea"},
     
     
     
     
     
      {"id": "97", "pergunta": "A Promotoria de Justiça possui procedimento ou ação judicial com o objetivo de buscar a implementação ou o aprimoramento — pelo ente federativo competente — da capacitação de agentes de segurança pública e/ou guardas civis municipais sobre o enfrentamento à violência doméstica e familiar contra a mulher?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "97.a", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "97", valor: "Sim" }},
      {"id": "98", "pergunta": "O(a) membro(a), quando do ajuizamento da ação penal, formula pedido de indenização à vítima com a fixação de valor mínimo para reparação dos danos, nos termos do art. 9º da Resolução CNMP nº 243/2021?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      
      {"id": "98.a", "pergunta": "O(a) membro(a) zela pelo direito de informação da vítima, tais como sobre seus direitos básicos, serviços de apoio, processos e outros meios de obtenção de reparação dos danos causados?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "98.b", "pergunta": "O(a) membro(a) fiscaliza a efetiva intimação da vítima em caso de liberdade provisória do autuado, nos termos do art. 21 da Lei nº 11.340/06?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      
      {"id": "99", "pergunta": "O(a) membro(a) tem fiscalizado, em sede de controle concentrado, se os órgãos de segurança pública dispõem de condições materiais, técnicas e operacionais necessárias para o exercício de suas atribuições na área do enfrentamento à violência doméstica e familiar contra a mulher?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      
      {"id": "100", "pergunta": "O(a) membro(a) possui atuação de recuperação e reeducação do agressor, nos termos da Recomendação CNMP nº 93/2022.", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "100.a", "pergunta": "Especificar.", "tipo": "textarea", dependeDe: { id: "100", valor: "Sim" }},
      {"id": "100.b", "pergunta": "O(a) membro(a) realiza atuação com perspectiva de gênero?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "100.c", "pergunta": "Especificar.", "tipo": "textarea"},

      {"id": "101", "pergunta": "A Promotoria de Justiça possui atuação por meio de ações, estratégias ou atividades específicas para o enfrentamento à discriminação à raça, à população LGBTQIAPN+ e à diversidade?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "101.a", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "101", valor: "Sim" }},
      {"id": "102", "pergunta": "A Promotoria de Justiça possui atuação, procedimento ou ação judicial com o objetivo de buscar a implementação ou o aprimoramento — pelo ente federativo competente — da capacitação de agentes de segurança pública e/ou guardas civis municipais sobre o enfrentamento à discriminação à raça, à população LGBTQIAPN+ e à diversidade, prevenindo eventuais abordagens, revistas e outras condutas discriminatórias?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "103", "pergunta": "Há atuação do(a) membro(a) para fiscalizar ou fomentar a promoção de políticas públicas garantidoras do respeito à diversidade sexual, de gênero e de raça no âmbito de sua atuação?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "103.a", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "103", valor: "Sim" }},
      {"id": "104", "pergunta": "Há monitoramento dos indicadores locais relativos à violência decorrente de discriminação à raça, à população LGBTQIAPN+ e à diversidade?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "104.a", "pergunta": "Informar o fluxo ou protocolo empregado.", "tipo": "textarea", dependeDe: { id: "104", valor: "Sim" }},
      {"id": "105", "pergunta": "O(a) membro(a), quando do ajuizamento da ação penal, formula pedido de indenização à vítima (artigo 387, inciso IV, do CPP)?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "106", "pergunta": "Na hipótese de omissão do juiz na fixação da indenização, são interpostos recursos?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "106.a", "pergunta": "Em caso positivo, informar o número do processo como exemplo de atuação.", "tipo": "textarea", dependeDe: { id: "106", valor: "Sim" }},
      {"id": "107", "pergunta": "O(a) membro(a) fiscaliza os parâmetros de acolhimento das pessoas LGBTQIAPN+ privadas de liberdade em estabelecimentos penais, nos termos da Recomendação CNMP nº 85/2021?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "107.a", "pergunta": "O(a) membro(a) realiza atuação integrada com Promotorias de Justiça com atribuição em homicídio na condução de ações preventivas?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "107.b", "pergunta": "Especifique com qual(is) Promotoria(s) de Justiça realiza atuação integrada ou, caso inexistente, justifique a ausência dessa articulação.", "tipo": "textarea"},
      {"id": "108", "pergunta": "A Promotoria de Justiça possui estratégia institucional específica voltada à atuação da defesa das pessoas com deficiência?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "108.a", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "108", valor: "Sim" }},
      {"id": "109", "pergunta": "O(a) membro(a) inspeciona pessoalmente, com periodicidade mínima anual, as Residências Inclusivas (RIs) e/ou outras instituições que prestem serviços de acolhimento a pessoas com deficiência, nos termos do art. 1º da Resolução CNMP nº 228/2021?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "109.a", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "109", valor: "Sim" }},
      {"id": "110", "pergunta": "Nos processos de curatela, o(a) membro(a) atua na fiscalização das respectivas prestações de contas e/ou em processos de tomada de decisão apoiada (TDA)?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "110.a", "pergunta": "Em caso negativo, há atuação integrada com a Promotoria de Justiça com atribuição nas áreas cível e de família?", "tipo": "radio", "opcoes": ["Sim", "Não"], dependeDe: { id: "110", valor: "Não" }},
      {"id": "110.b", "pergunta": "Especificar a atuação integrada.", "tipo": "textarea", dependeDe: { id: "110", valor: "Não" }},
      {"id": "111", "pergunta": "Há articulação ou atuação integrada com o RECOMEÇAR ou com o NAVID, quando necessário?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "111.a", "pergunta": "Em caso positivo, informar o número do processo para exemplificar a atuação.", "tipo": "textarea", dependeDe: { id: "111", valor: "Sim" }},
      {"id": "112", "pergunta": "O(a) membro(a), quando do ajuizamento da ação penal, formula pedido de indenização à vítima (artigo 387, inciso IV, do CPP)?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "113", "pergunta": "Na hipótese de omissão do juiz na fixação de indenização, são interpostos recursos?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "114", "pergunta": "Há presos da comarca correicionada que estejam custodiados em outras jurisdições?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "114.a", "pergunta": "Caso positivo, informar o quantitativo.", "tipo": "textarea", dependeDe: { id: "114", valor: "Sim" }},
      {"id": "115", "pergunta": "Como ocorre o cumprimento de pena para os sentenciados em regime semiaberto e aberto?", "tipo": "textarea"},
      {"id": "116", "pergunta": "O(a) membro(a) estimula, de alguma forma, o desenvolvimento de ações para a remissão de pena?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "116.a", "pergunta": "Especificar.", "tipo": "textarea", dependeDe: { id: "116", valor: "Sim" }},
      {"id": "117", "pergunta": "O(a) membro(a) tem fiscalizado, em sede de controle concentrado, se os órgãos de segurança pública dispõem de condições materiais, técnicas e operacionais necessárias e compatíveis para o exercício de suas atribuições?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "117.a", "pergunta": "Em caso positivo, informar o número do processo para exemplificar a atuação.", "tipo": "textarea", dependeDe: { id: "117", valor: "Sim" }},
      {"id": "118", "pergunta": "Nas hipóteses de promoção de arquivamento das investigações criminais, a vítima e/ou seus familiares têm sido notificados sobre o pronunciamento do Ministério Público, conforme art. 11, § 2º, da Resolução CNMP nº 279/2023?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "118.a", "pergunta": "Em caso positivo, informar o número do processo para exemplificar a atuação.", "tipo": "textarea", dependeDe: { id: "118", valor: "Sim" }},
      {"id": "119", "pergunta": "O(a) membro(a) acompanha as investigações dos crimes que envolvam letalidade e vitimização policiais a partir das primeiras 24 horas da ocorrência, conforme art. 11, § 3º, da Resolução CNMP nº 279/2023?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "119.a", "pergunta": "Em caso positivo, informar o número do processo para exemplificar a atuação.", "tipo": "textarea", dependeDe: { id: "119", valor: "Sim" }},
      {"id": "120", "pergunta": "O(a) membro(a) instaurou procedimento administrativo para verificar a existência e o adequado funcionamento de Programa de Integridade na Administração Pública, conforme o art. 4º da Resolução nº 305/2025-CNMP?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "120.a", "pergunta": "Em caso positivo, informar o número do processo/procedimento.", "tipo": "textarea", dependeDe: { id: "120", valor: "Sim" }},
      {"id": "121", "pergunta": "O(a) membro(a) tem celebrado acordo de não persecução cível quando este se mostra proporcional e suficiente para a proteção do patrimônio público e da moralidade administrativa, nos termos do art. 2º da Resolução nº 306/2025-CNMP?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "121.a", "pergunta": "Em caso positivo, informar o número do processo/procedimento.", "tipo": "textarea", dependeDe: { id: "121", valor: "Sim" }},
      {"id": "121.b", "pergunta": "Em caso afirmativo, o acordo de não persecução cível tem contemplado a aplicação de uma ou mais sanções previstas na Lei nº 8.429/1992, conforme o art. 3º da Resolução nº 306/2025-CNMP?", "tipo": "radio", "opcoes": ["Sim", "Não"], dependeDe: { id: "121", valor: "Sim" }},
      {"id": "121.c", "pergunta": "Em caso positivo, informar o número do processo/procedimento.", "tipo": "textarea", dependeDe: { id: "121", valor: "Sim" }},
      {"id": "122", "pergunta": "O(a) membro(a) tem fiscalizado se o ente público observa os parâmetros legais mínimos obrigatórios que devem constar nos Portais da Transparência, conforme a Nota Técnica CAO-PDC nº 5/2025?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "122.a", "pergunta": "Em caso positivo, informar o número do processo/procedimento para exemplificar a atuação.", "tipo": "textarea", dependeDe: { id: "122", valor: "Sim" }},
      {"id": "123", "pergunta": "O(a) membro(a) realiza vistorias em hospitais, UPAs e postos de saúde para verificar condições de higiene, presença de médicos, estoque de medicamentos e funcionamento de equipamentos?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "123.a", "pergunta": "Em caso positivo, qual a periodicidade e o procedimento?", "tipo": "textarea", dependeDe: { id: "123", valor: "Sim" }},
      {"id": "124", "pergunta": "O(a) membro(a) fiscaliza a correta aplicação de verbas públicas destinadas à saúde e o cumprimento de metas de vacinação e saneamento?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "124.a", "pergunta": "Em caso positivo, informar o número do procedimento.", "tipo": "textarea", dependeDe: { id: "124", valor: "Sim" }},
      {"id": "125", "pergunta": "O(a) membro(a) tem atuado para reduzir o tempo de espera por cirurgias, exames e consultas especializadas?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "125.a", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "125", valor: "Sim" }},
      {"id": "126", "pergunta": "O(a) membro(a) tem atuado visando assegurar o atendimento prioritário e adequado a idosos, crianças, pessoas com deficiências e pacientes com doenças raras ou transtornos mentais?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "126.a", "pergunta": "Em caso positivo, especificar.", "tipo": "textarea", dependeDe: { id: "126", valor: "Sim" }},
      {"id": "127", "pergunta": "O(a) membro(a) tem investigado desvios de recursos, fraude em licitações na área da saúde ou omissão de gestores que coloquem a vida da população em risco?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "127.a", "pergunta": "Em caso positivo, informar o número do procedimento.", "tipo": "textarea", dependeDe: { id: "127", valor: "Sim" }},
      {"id": "128", "pergunta": "O Município tem TFD (Tratamento Fora do Domicílio)?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "128.a", "pergunta": "Em caso negativo, especificar como é feita a transferência de pacientes para a rede estadual.", "tipo": "textarea", dependeDe: { id: "128", valor: "Não" }},
      {"id": "129", "pergunta": "Existe CAPS no Município?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "129.a", "pergunta": "Em caso afirmativo, especificar o tipo.", "tipo": "textarea", dependeDe: { id: "129", valor: "Sim" }},
      {"id": "130", "pergunta": "O(a) membro(a) fiscaliza os repasses fundo a fundo?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "130.a", "pergunta": "Em caso positivo, informar o número do procedimento.", "tipo": "textarea", dependeDe: { id: "130", valor: "Sim" }},
      {"id": "131", "pergunta": "O Município possui usina própria de oxigênio?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "131.a", "pergunta": "Em caso negativo, como é feito o abastecimento do hospital?", "tipo": "textarea", dependeDe: { id: "131", valor: "Não" }},
      {"id": "132", "pergunta": "O Município possui sistema de tratamento de água distribuída para a população?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "132.a", "pergunta": "Em caso positivo, informar o número do procedimento.", "tipo": "textarea", dependeDe: { id: "132", valor: "Sim" }},
      {"id": "132.b", "pergunta": "Em caso negativo, informar o número do procedimento instaurado, se houver.", "tipo": "textarea", dependeDe: { id: "132", valor: "Não" }},
      {"id": "133", "pergunta": "O(a) membro(a), quando atua na responsabilização por danos ambientais e climáticos, observa o princípio da reparação integral, levando em conta todas as dimensões socioambientais, incluindo os impactos sobre a flora, fauna, clima, solo, ar, água e bem-estar coletivo?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "133.a", "pergunta": "Em caso positivo, informar o número do processo para exemplificar a atuação.", "tipo": "textarea", dependeDe: { id: "133", valor: "Sim" }},
      {"id": "134", "pergunta": "O(a) membro(a) adota medidas preventivas e articuladas para o combate às queimadas e desmatamento?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "134.a", "pergunta": "Em caso positivo, informar o número do processo para exemplificar a atuação.", "tipo": "textarea", dependeDe: { id: "134", valor: "Sim" }},
      {"id": "135", "pergunta": "O(a) membro(a) correicionado(a) fiscaliza a política de descarte de resíduos sólidos e de lixo hospitalar?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "135.a", "pergunta": "Em caso positivo, informar o número do procedimento.", "tipo": "textarea", dependeDe: { id: "135", valor: "Sim" }},
      {"id": "136", "pergunta": "O Município possui Plano Diretor?", "tipo": "radio", "opcoes": ["Sim", "Não"]},
      {"id": "136.a", "pergunta": "O(a) membro(a) correicionado(a) fiscaliza a ocupação do solo e o parcelamento urbano para evitar o crescimento desordenado que degrada o ecossistema local?", "tipo": "radio", "opcoes": ["Sim", "Não"], dependeDe: { id: "136", valor: "Sim" }},
      {"id": "136.b", "pergunta": "Em caso positivo, informar o número do procedimento.", "tipo": "textarea", dependeDe: { id: "136.a", valor: "Sim" }}
    ]
  },
  {
    "nome": "Avaliação Complementar da Atuação Ministerial",
    "campos": [
      {"id": "137", "pergunta": "Quais as principais áreas em que o(a) membro(a) tem encontrado entraves nas demandas encaminhadas ao poder público.(Exemplo: Não atendimento ou demora nas devolutivas)", "tipo": "textarea"},
      {"id": "138", "pergunta": "O(a) membro(a) tem sugestões voltadas à melhoria da atuação?", "tipo": "textarea"},
      {"id": "139", "pergunta": "O(a) membro(a) tem experiências inovadoras e/ou boas práticas, independentemente de estarem registradas institucionalmente, que queira indicar?", "tipo": "textarea"},
      {"id": "140", "pergunta": "Observações adcionais.", "tipo": "textarea"},
       ]
  }
]};
